version: '3.8'

services:
  jobportal-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_portal_db
    ports:
      - "3333:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - jobportal-net

  jobportal-app:
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://jobportal-db:3306/job_portal_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - jobportal-db
    networks:
      - jobportal-net

networks:
  jobportal-net:

volumes:
  mysql-data:
