apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-portal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-portal
  template:
    metadata:
      labels:
        app: job-portal
    spec:
      containers:
        - name: job-portal-container
          image: visimihasi/job-portal:latest
          ports:
            - containerPort: 8080
