apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobportal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobportal-app
  template:
    metadata:
      labels:
        app: jobportal-app
    spec:
      containers:
        - name: jobportal-app
          image: visimihasi/job-portal:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://jobportal-db:3306/job_portal_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: jobportal-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # Optional: You can specify the port here, or let Kubernetes assign one
  selector:
    app: jobportal-app
  type: NodePort  # Change this to NodePort for local environments
