apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the size as needed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobportal-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobportal-db
  template:
    metadata:
      labels:
        app: jobportal-db
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"  # Set the root password here
            - name: MYSQL_DATABASE
              value: "job_portal_db"  # The database that will be created
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jobportal-db
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30006
  selector:
    app: jobportal-db

