name: CI/CD Pipeline

on:
  push:
    branches:
      - Deployment

permissions:
  contents: write
  actions: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Check out the repo
        uses: actions/checkout@v2

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Grant execute permissions to Gradle wrapper
      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x ./gradlew

      # Build the application with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Read the current version from version.properties
      - name: Get current version
        id: version
        run: |
          VERSION=$(cat version.properties | cut -d'=' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "The current version is $VERSION"

      # Build and push Docker image with the version from version.properties
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DOCKER/Dockerfile
          push: true
          tags: visimihasi/job-portal:${{ env.VERSION }}
          build-args: |
            JAR_FILE=job-portal-${{ env.VERSION }}.jar

      # Commit and push new version number if you need to increment it (optional)
      - name: Commit new version and push
        run: |
          NEW_VERSION="${{ env.VERSION }}"
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add version.properties
          git commit -m "Bump version to $NEW_VERSION"
          git push

      # Output the new version
      - name: Output new version
        run: echo "The new Docker image version is ${{ env.VERSION }}"
