name: CI/CD Pipeline

on:
  push:
    branches:
      - Deployment

permissions:
  contents: write
  actions: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Calculate new version
        run: |
          # Read the current version (ensure correct format)
          VERSION=$(grep '^version=' version.properties | cut -d'=' -f2)

          # Increment only the last digit (e.g., 1.0.0 → 1.0.1)
          NEW_VERSION=$(echo $VERSION | awk -F. '{print $1"."$2"."($3+1)}')

          # Overwrite version.properties with the new version
          echo "version=$NEW_VERSION" > version.properties

          # Print the new version
          echo "New version: $NEW_VERSION"

          # Configure Git
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          # Commit the version update
          git add version.properties
          git commit -m "Bump version to $NEW_VERSION"

          # Authenticate using GH_PAT and push changes
          git remote set-url origin "https://x-access-token:${{ secrets.GH_PAT }}@github.com/VisiMihasi/JobPortal.git"
          git push origin HEAD:Deployment --force

          # Set the new version as an environment variable for later use
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: visimihasi/job-portal:${{ env.NEW_VERSION }}


      - name: Output new version
        run: echo "The new Docker image version is ${{ env.NEW_VERSION }}"
