name: CI/CD Pipeline

on:
  push:
    branches:
      - Deployment

permissions:
  contents: write
  actions: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Check out the repo
        uses: actions/checkout@v2

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Grant execute permissions to Gradle wrapper
      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x ./gradlew

      # Build the application with Gradle
      - name: Build with Gradle
        run: ./gradlew build -x test

      # Read current version from version.properties
      - name: Read current version
        run: |
          VERSION=$(cat version.properties | cut -d'=' -f2)
          echo "Current version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Build and push Docker image with both version and latest tag
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            visimihasi/job-portal:${{ env.VERSION }}
            visimihasi/job-portal:latest

