name: CI/CD Pipeline

on:
  push:
    branches:
      - Deployment

permissions:
  contents: write
  actions: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Calculate new version
        run: |
          # Read the current version from version.properties
          VERSION=$(grep '^version=' version.properties | cut -d'=' -f2)

          # Split the version into major, minor, and patch components, and increment the patch version
          MAJOR=$(echo $VERSION | cut -d '.' -f1)
          MINOR=$(echo $VERSION | cut -d '.' -f2)
          PATCH=$(echo $VERSION | cut -d '.' -f3)

          # Increment the patch version
          NEW_PATCH=$((PATCH+1))

          # Create the new version string
          NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"

          # Write the new version to version.properties
          echo "version=$NEW_VERSION" > version.properties

          # Print the new version for debugging purposes
          echo "New version: $NEW_VERSION"

          # Configure Git for commit
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          # Commit the updated version.properties file
          git add version.properties
          git commit -m "Bump version to $NEW_VERSION"

          # Authenticate using the GitHub PAT token and push changes to the Deployment branch
          git remote set-url origin "https://x-access-token:${{ secrets.GH_PAT }}@github.com/VisiMihasi/JobPortal.git"
          git push origin HEAD:Deployment --force

          # Set the new version as an environment variable for later use
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: visimihasi/job-portal:${{ env.NEW_VERSION }}
